# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x291d14ff
rootcolor = 0x291d14ff
bordercolor = 0x74675fff
dropcolor = 0xe49c6780
splitcolor = 0xa1cc66ff
focuscolor = 0xe49c67ff
maximizescreencolor = 0xd6cd5cff
urgentcolor = 0x7f4f2cff
scratchpadcolor = 0xa1cc66ff
globalcolor = 0x8d420cff
overlaycolor = 0x6f6810ff
jump_label_decorate_fg_color = 0xf3f2f2ff
jump_label_decorate_bg_color = 0x533a28ff
jump_label_decorate_focus_fg_color = 0x251e18ff
jump_label_decorate_focus_bg_color = 0xe49c67ff
jump_label_decorate_border_color = 0x74675fff
