
palette = "noctalia"

# Só pra trocar onde aparece o $time
format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$nats\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$hg_state\
$pijul_channel\
$docker_context\
$package\
$bun\
$c\
$cmake\
$cobol\
$cpp\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$gleam\
$golang\
$gradle\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$lua\
$maven\
$mojo\
$nim\
$nodejs\
$ocaml\
$odin\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$xmake\
$zig\
$buf\
$guix_shell\
$nix_shell\
$conda\
$pixi\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$mise\
$crystal\
$custom\
$sudo\
$cmd_duration\
$time\
$line_break\
$jobs\
$battery\
$status\
$container\
$netns\
$os\
$shell\
$character"""

[time]
disabled = false
use_12hr = true


# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#78824b"
red       = "#685742"
green     = "#5f875f"
yellow    = "#b36d43"
cyan      = "#c9a554"
magenta   = "#bb7744"
white     = "#d7c483"
black     = "#000000"

# Extended palette (Catppuccin-compatible names)
rosewater = "#d08f5f"
flamingo  = "#8a6f5c"
pink      = "#d89a66"
mauve     = "#bb7744"
maroon    = "#8a6f5c"
peach     = "#d08f5f"
teal      = "#c9a554"
sky       = "#e0c080"
sapphire  = "#95a064"
lavender  = "#d89a66"

# Text shades
text      = "#c2c2b0"
subtext1  = "#d7c483"
subtext0  = "#666666"

# Surface shades
overlay2  = "#666666"
overlay1  = "#666666"
overlay0  = "#000000"
surface2  = "#000000"
surface1  = "#000000"
surface0  = "#222222"
base      = "#222222"
mantle    = "#222222"
crust     = "#222222"
# <<< NOCTALIA STARSHIP PALETTE <<<
