require("options")
require("keymaps")
require("commands")
require("packs.mini")
require("packs.gitsigns")
require("packs.codediff")
require("packs.surround")
require("packs.autosave")
require("packs.snacks")
require("packs.telescope")
require("packs.treesitter")
require("packs.lsp")
require("packs.flash")
require("packs.conform")
require("packs.claude")
require("packs.supermaven")
require("packs.hardtime")
require("packs.base16")
require("packs.transparent")

local ok, matugen = pcall(require, 'matugen')
if ok then matugen.setup() end
